### ISSUE TITLE
Add a forget password page

### ISSUE THREAD

**Issue by hayat-tamboli** [InSync-HQ/InSync_FlutterApp#47] opened 2022-10-01 12:55 UTC
**Is your feature request related to a problem? Please describe.**
I don't remember my password and I don't know how to log in

**Describe the solution you'd like**

- [x] Add a forget password page
- [x] button in login page to get to it

**Comment by WaniAthar** [comment] 2022-10-01 13:27
can i help you with this?

**Comment by hayat-tamboli** [comment] 2022-10-01 13:48
> can i help you with this?

Sure, this is how the screen should look 

https://www.figma.com/file/Lps2BgnGU0KZw3tiq1uF94/Insync-Forgot-password-page?node-id=0%3A1
![image](https://user-images.githubusercontent.com/55529269/193412576-3bc1def8-8a12-48d7-8cbc-0df14a10c5dd.png)

Happy coding!

**Comment by WaniAthar** [comment] 2022-10-01 13:49
@hayat-tamboli  assign me this issue

**Comment by WaniAthar** [comment] 2022-10-01 13:52
can you tell me the font you used? @hayat-tamboli

**Comment by hayat-tamboli** [comment] 2022-10-01 13:53
> can you tell me the font you used? @hayat-tamboli

General Sans

https://www.fontshare.com/fonts/general-sans

**Comment by WaniAthar** [comment] 2022-10-01 14:18
**build error**



FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.7/userguide/gradle_daemon.html
Process command line: C:\Program Files\Java\jdk-11.0.14\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx1536M -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\athar\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe\gradle-6.7\lib\gradle-launcher-6.7.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.7        
Please read the following process output to find out more:
-----------------------
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000a0000000, 132120576, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 132120576 bytes for Failed to commit area from 0x00000000a0000000 to 0x00000000a7e00000 of length 132120576.
# An error report file with more information is saved as:
# C:\Users\athar\.gradle\daemon\6.7\hs_err_pid23684.log


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Running Gradle task 'assembleDebug'...                            165.2s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hayat-tamboli** [comment] 2022-10-01 19:50
Try this

https://stackoverflow.com/a/34734684

Also don't try to open the app in windows or chrome, it might not run, it works only in android and ios

**Comment by WaniAthar** [comment] 2022-10-01 20:00
again the same error.
i think your jdk version is different from mine
can you check once

**Comment by hayat-tamboli** [comment] 2022-10-01 20:26
@Manas1820 can you help us here

**Comment by Manas1820** [comment] 2022-10-01 20:27
Yup looking into it !

**Comment by WaniAthar** [comment] 2022-10-01 20:29
i can try one thing..
create a new flutter project 
and copy all the files from the existing project and paste into the new one
whats say?

**Comment by Manas1820** [comment] 2022-10-01 20:30
Won't recommend that until and unless it's the last option

**Comment by Manas1820** [comment] 2022-10-01 20:31
Wait for a while I will fix it in a few hours

**Comment by WaniAthar** [comment] 2022-10-01 20:32
okay

**Comment by Manas1820** [comment] 2022-10-02 06:47
@hayat-tamboli  @WaniAthar check its fixed now after my pr is merged

**Comment by WaniAthar** [comment] 2022-10-02 07:00
okay

**Comment by WaniAthar** [comment] 2022-10-02 08:04
build success

**Comment by WaniAthar** [comment] 2022-10-02 09:30
> > can i help you with this?
> 
> Sure, this is how the screen should look
> 
> https://www.figma.com/file/Lps2BgnGU0KZw3tiq1uF94/Insync-Forgot-password-page?node-id=0%3A1 ![image](https://user-images.githubusercontent.com/55529269/193412576-3bc1def8-8a12-48d7-8cbc-0df14a10c5dd.png)
> 
> Happy coding!

do you want me to add a back button?? @Manas1820 @hayat-tamboli

**Comment by Manas1820** [comment] 2022-10-02 09:32
@hayat-tamboli looks like a good idea

**Comment by hayat-tamboli** [comment] 2022-10-02 09:59
Sure go for it

**Comment by hayat-tamboli** [comment] 2022-10-02 10:23
Do add the back button in the top app bar

**Comment by WaniAthar** [comment] 2022-10-02 11:54
![flutter_01](https://user-images.githubusercontent.com/83573286/193452654-ca31552f-2f5a-4eed-b646-cdfdd376b357.png)
![flutter_02](https://user-images.githubusercontent.com/83573286/193452655-cf1f7250-0123-4ebf-a981-2a1b97f956e4.png)

**Comment by WaniAthar** [comment] 2022-10-02 13:55
@hayat-tamboli  i have created a pull request, please check

**Comment by hayat-tamboli** [comment] 2022-10-02 14:04
@all-contributors please add @WaniAthar for code

**Comment by hayat-tamboli** [comment] 2022-10-02 14:06
The page looks great, well done @WaniAthar  🚀, I will close this issue. we will add functionality to this page soon ✌

**Closed as completed** 2022-10-02 14:06 UTC
Labels: good first issue, hacktoberfest
